matrix:
  include:
   - os: osx
     osx_image: xcode10
     env: CC=gcc-8 CXX=g++-8
     language: java

cache:
  directories:
  - $HOME/.m2
  - $HOME/Library/Caches/Homebrew

install:
  - brew install gcc@8

script:
  - mkdir build
  - cd build && CC=gcc-8 CXX=g++-8 cmake .. && make
