version: 1.0.'{build}'
image: Visual Studio 2017

branches:
  only:
    - master

skip_tags: true
skip_non_tags: true
skip_branch_with_pr: true
platform: x64
configuration: Release

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

build_script:
  - build.bat
  - mvn -DskipTests -q clean package

artifacts:
  - path: PDCurses-3.7\wincon\pdcurses.dll
    name: pdcurses DLL