version: 1.0.'{build}'
image: Visual Studio 2013

branches:
  only:
    - master

skip_tags: true
skip_non_tags: true
skip_branch_with_pr: true
platform: x64
configuration: Release

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

build_script:
  - ps: Start-FileDownload 'https://github.com/wmcbrine/PDCurses/archive/3.8.zip'
  - build.bat
  - mvn -DskipTests -q clean package

artifacts:
  - path: target\curses4j-1.0.0-SNAPSHOT.jar
    name: curses4j library (JAR)
