version: 1.0.'{build}'

image:
 - ubuntu1804
 - Visual Studio 2017

platform: x64
configuration: Release

stack: jdk 1.8

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

build_script:
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cmd: build.bat
  - cmd: mvn -DskipTests -q clean package
  - sh: sudo apt-get -q --yes install cmake
  - sh: sudo apt-get -q --yes install libncurses-dev
  - sh: mkdir build && cd build && cmake .. && make && strip libcurses4j.so && cd ..
  - sh: cp build/libcurses4j.so src/main/resources/META-INF
  - sh: mvn -DskipTests -q clean package

artifacts:
  - path: target\curses4j-1.1.0.jar
    name: curses4j library (JAR)
